version: '3.8'  # You can specify the version if you want to

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: cameracapstone-db
    container_name: cameracapstone
    user: root
    networks:
      - demo
    environment:
      SA_PASSWORD: "sa@root123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql/data
      - mssql-log:/var/opt/mssql/log
      - mssql-secrets:/var/opt/mssql/secrets

  cameraservicesplatform.backend.api:
    image: ${DOCKER_REGISTRY-}cameraservicesplatformbackendapi
    build:
      context: .
      dockerfile: CameraServicesPlatform.BackEnd.API/Dockerfile
    container_name: cameracapstone-be
    networks:
      - demo
    ports:
      - "3000:8080"
      - "2602:8080"
      - "3001:8081"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DBVPS=Server=14.225.220.108;Database=CameraCapstone;User Id=sa;Password=sa@root123@;TrustServerCertificate=True;

networks:
  demo:
    driver: bridge

volumes:
  sqlserverdata:
  mssql-log:
  mssql-secrets:

