version: '3.8'  # Specify the Docker Compose version

services:
  camera_services:
    build:
      context: .  # Current directory
      dockerfile: CameraServicesPlatform.BackEnd.API/Dockerfile  # Name of your Dockerfile
    ports:
      - "2602:8080"
      - "3000:8080"  # Map host port 3000 to container port 8080 (local)
      - "8081:8081"  # Map host port 8081 to container port 8081 (optional)
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  # Set environment variable
    networks:
      - camera_network  # Use a specific network

networks:
  camera_network:
    driver: bridge  # Use the bridge driver for networking
