version: '3.4'

services:
  

  cameracapstone-be:
    image: ${DOCKER_REGISTRY-}cameracapstone
    build:
      context: .
      dockerfile: CameraServicesPlatform.BackEnd.API/Dockerfile
    container_name: cameracapstone-be
    networks:
      - demo
    ports:
      - "3000:8080"    # Internal API access
      - "2602:8080"    # Map container port 8080 to host port 2602
      - "443:443"      # External access for HTTPS
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DBVPS: "Server=14.225.220.108;Database=CameraCapstone;User Id=sa;Password=sa@root123@;TrustServerCertificate=True;"

networks:
  demo:
    driver: bridge

volumes:
  sqlserverdata:
  mssql-log:
  mssql-secrets:
