version: '3.8'  # Optional but can be kept for clarity

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver-db
    container_name: sqlserver
    networks:
      - demo
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433"
    volumes:
      - sqlserverdata:/var/opt/mssql/data
      - mssql-log:/var/opt/mssql/log
      - mssql-secrets:/var/opt/mssql/secrets

  cameraservicesplatform-be:  # Use a consistent service name
    image: ${DOCKER_REGISTRY-}cameraservicesplatformbackendapi
    build:
      context: .
      dockerfile: CameraServicesPlatform.BackEnd.API/Dockerfile
    networks:
      - demo
    ports:
      - "2602:8080"   # Map port 8080 in the container to port 2602 on the host
      - "443:443"      # HTTPS port, if needed
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DBVPS=Server=14.225.220.108;Database=CameraCapstone;User Id=sa;Password=root123@;TrustServerCertificate=True;

networks:
  demo:
    driver: bridge

volumes:
  sqlserverdata:
  mssql-log:
  mssql-secrets:
