version: '3.3'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver-db
    container_name: sqlserver
    networks:
      - demo
    environment:
      SA_PASSWORD: "sa@root123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./containers/capstone.backend.db:/var/opt/mssql/data

  camera.api: 
    image: "${DOCKER_REGISTRY:-}camera.api"
    build:
      context: .  
      dockerfile: CameraServicesPlatform.BackEnd.API/Dockerfile
    container_name: camera.api
    networks:
      - demo
    ports:
      - "2602:8080"
      - "443:8081"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DBVPS: "Server=14.225.220.108;Database=CameraCapstone;User Id=sa;Password=root123@;TrustServerCertificate=True;"

networks:
  demo:
    driver: bridge

volumes:
  sqlserverdata:
  mssql-log:
  mssql-secrets:
