version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver-db
    container_name: sqlserver
    user: "root"
    networks:
      - demo
    environment:
      SA_PASSWORD: "sa@root123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql/data
      - mssql-log:/var/opt/mssql/log
      - mssql-secrets:/var/opt/mssql/secrets

  camera.api: 
    image: "${DOCKER_REGISTRY:-}camera.api"
    build:
      context: .
      dockerfile: CameraServicesPlatform.BackEnd.API/Dockerfile
    container_name: camera.api
    networks:
      - demo
    ports:
      - "3005:8080"
      - "2602:8080" 
      - "443:8081"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DBVPS: "Server=sqlserver-db;Database=CameraCapstone;User Id=sa;Password=sa@root123@;TrustServerCertificate=True;"

networks:
  demo:
    driver: bridge

volumes:
  sqlserverdata:
  mssql-log:
  mssql-secrets:
